@startuml

actor User
participant Application
participant Community as "Community (Self) \n AWS Healthlate (S3)"
participant PrimaryCareAdaptor
participant NHSEnglandAdaptor
participant AcuteCareAdaptor
participant RegionalAdaptor
participant EMIS
participant TPP
participant NRL as "NRL, BARS and eRS"
participant EPIC
participant Cerner
participant XDS as "IHE XDS"
participant MHD as "IHE MHD"

User -> Application : Find Clinical Notes and Patient Documents
opt Community
Application-> Community: Find Documents
Community --> Application : Matching Documents (FHIR)
end
opt Primary Care
Application-> PrimaryCareAdaptor: Find Documents
opt EMIS
PrimaryCareAdaptor -> EMIS: Find Documents (IM1)
EMIS --> PrimaryCareAdaptor : Matching Documents (IM1)
else TPP
PrimaryCareAdaptor -> TPP: Find Documents (IM1)
TPP --> PrimaryCareAdaptor : Matching Documents (IM1)
end
PrimaryCareAdaptor --> Application : Matching Documents (FHIR)
end
opt NHS England
Application-> NHSEnglandAdaptor: Find Documents
loop for NRL, BARS and eRS (as required)
NHSEnglandAdaptor -> NRL: Find Documents
NRL --> NHSEnglandAdaptor: Matching Documents (FHIR)
end
NHSEnglandAdaptor --> Application: Matching Documents (FHIR modified)
end
opt Acute Care
  Application-> AcuteCareAdaptor: Find Documents
  opt Cerner
   AcuteCareAdaptor -> Cerner: Find Documents
   Cerner --> AcuteCareAdaptor: Matching Documents (FHIR)
   else EPIC
   AcuteCareAdaptor -> EPIC: Find Documents
   EPIC --> AcuteCareAdaptor: Matching Documents (FHIR)
  end
NHSEnglandAdaptor --> Application: Matching Documents (FHIR)
end
opt Regional
  Application-> RegionalAdaptor: Find Documents
  opt XDS e.g. OneLondon
   RegionalAdaptor -> XDS: Find Documents
   XDS --> RegionalAdaptor: Matching Documents (XDS Document Metadata)
   else MHD e.g. Yorkshire and Humberside Care Record
   RegionalAdaptor -> MHD: Find Documents
   MHD --> RegionalAdaptor: Matching Documents (FHIR R4 or STU3)
  end
RegionalAdaptor --> Application: Matching Documents (FHIR)
end

Application -> User: Documents Search Results

@enduml
