@startuml

actor User
participant Application
participant PrimaryCareAdaptor
participant NHSEnglandAdaptor
participant AcuteCareAdaptor
participant EMIS
participant TPP
participant PDS
participant EPIC
participant Cerner


User -> Application : Find Patient
opt EMIS
Application-> PrimaryCareAdaptor: Find Patient
PrimaryCareAdaptor -> EMIS: Find Patient (IM1)
EMIS --> PrimaryCareAdaptor : Matching Patients (IM1)
PrimaryCareAdaptor --> Application : Matching Patients (FHIR)
else TPP
Application-> PrimaryCareAdaptor: Find Patient
PrimaryCareAdaptor -> TPP: Find Patient (IM1)
TPP --> PrimaryCareAdaptor : Matching Patients (IM1)
PrimaryCareAdaptor --> Application : Matching Patients (FHIR)
else NHS England PDS
Application-> NHSEnglandAdaptor: Find Patient
NHSEnglandAdaptor -> PDS: Find Patient
PDS --> NHSEnglandAdaptor: Matching Patients (FHIR)
NHSEnglandAdaptor --> Application: Matching Patients (FHIR modified)
else Acute Care
Application-> AcuteCareAdaptor: Find Patient
opt Cerner
AcuteCareAdaptor -> Cerner: Find Patient
Cerner --> AcuteCareAdaptor: Matching Patients (FHIR)
else EPIC
AcuteCareAdaptor -> EPIC: Find Patient
EPIC --> AcuteCareAdaptor: Matching Patients (FHIR)
end
AcuteCareAdaptor --> Application: Matching Patients (FHIR)
end
Application -> User: Patient Search Results


@enduml
