@startuml

skinparam svgDimensionStyle false

component "Data Capture Application" as DataCaptureApplication
note left
The data capture must conform to the definition in a FHIR Questionnaire
Archetypes/templates definitions must be converted to HL7 FHIR
end note

component "Existing Clinical Data Service" as prepopulate
note right
Retrieve existing data from connected CDR's.
Follows [[https://build.fhir.org/ig/HL7/sdc/populate.html HL7 SDC Form Population]]
end note

component "Testing Service" as FHIRTestingService
note right
[[https://hl7.org/fhir/R4/validation.html HL7 FHIR Validation]] Checks clinical coding is correct,
using NHS England Ontology Service
end note

component "Clinical Data Extraction Service" as extract
note right
Follows [[https://build.fhir.org/ig/HL7/sdc/extraction.html HL7 SDC Form Extraction]]
and converts coded questions and answers into Observations.
Perform any SNOMED/LOINC mappings
end note

component "Clinical Data Repository" as CDR
note right
Either local and/or external (GP systems) CDR

Observations persisted for reuse in other forms.
end note

component "Form Repository" as FR
note right
Form/template persisted for reference.
Can potentially convert this into archetype/template
for external repositories
end note

DataCaptureApplication -d-> FHIRTestingService: HL7 FHIR QuesionnaireResponse
DataCaptureApplication <-r-> prepopulate: FHIR Questionnaire and patient id
FHIRTestingService -d-> extract : HL7 FHIR QuesionnaireResponse
FHIRTestingService -d-> FR : HL7 FHIR QuestionnaireResponse
extract -d-> CDR : HL7 FHIR Observations

@enduml
