@startuml

component ClientApplication

interface facade as "[[ActorDefinition-ServiceFacade.html Service Facade]]"
note right
[[CapabilityStatement-IM1PatientEMISFacade.html Facade - IM1 Patient EMIS]]
end note

component "[[ActorDefinition-ClinicalDataRepository.html Clinical Data Repository]]" as CDR
note right
[[https://digital.nhs.uk/services/gp-it-futures-systems/im1-pairing-integration/interface-mechanisms-guidance#partner-api IM1 Partner API EMIS]]
end note

ClientApplication -d-> facade

facade -d-> CDR

@enduml
