@startuml

component ClientApplication as "Client Application"

interface facade as "[[ActorDefinition-ServiceFacade.html Service Facade]]"
note right
[[CapabilityStatement-IM1TransactionEMISFacade.html Facade - IM1 Transaction EMIS]]
end note

component "[[ActorDefinition-ClinicalDataRepository.html Clinical Data Repository]]" as CDR
note right
[[https://digital.nhs.uk/services/gp-it-futures-systems/im1-pairing-integration/interface-mechanisms-guidance#transaction IM1 Transaction EMIS]]
end note

ClientApplication -d-> facade

facade -d-> CDR

@enduml
