@startuml

component ClientApplication

interface facade as "[[ActorDefinition-ServiceFacade.html Service Facade]]"
note right
[[CapabilityStatement-ODSFacade.html Facade - Organisation Data Service - FHIR API]]
end note

component "[[ActorDefinition-DirectoryService.html Directory Service]]" as DirectoryService
note right
[[https://digital.nhs.uk/developer/api-catalogue/organisation-data-service-fhir Organisation Data Service - FHIR API]]
end note

ClientApplication -d-> facade

facade -d-> DirectoryService

@enduml
