@startuml

actor User
participant Application
participant PrimaryCareAdaptor
participant IPAAdaptor
participant EMIS
participant TPP
participant MCSD_MPI
participant NHSEnglandAdaptor
participant PDS


User -> Application : Select Patient
opt current (user = practitioner)
Application-> PrimaryCareAdaptor: Find Patient
PrimaryCareAdaptor -> EMIS: Find Patient (IM1)
EMIS --> PrimaryCareAdaptor : Matching Patients (IM1)
PrimaryCareAdaptor --> Application : Mathcing Patients (FHIR)
Application -> Application : Select Patient
else future (user = practioner)
Application-> NHSEnglandAdaptor: Find Patient
NHSEnglandAdaptor -> PDS: Find Patient
PDS --> NHSEnglandAdaptor: Matching Patients (FHIR)
NHSEnglandAdaptor --> Application: Matching Patients (FHIR corrected)
Application -> Application: Select Patient
Application -> PrimaryCareAdaptor: Get Patient
PrimaryCareAdaptor-> MCSD_MPI: Get GP Endpoint
MCSD_MPI --> PrimaryCareAdaptor: Endpoint

opt system = EMIS
PrimaryCareAdaptor -> EMIS: Get Patient (IM1)
EMIS --> PrimaryCareAdaptor: FHIR Patient
else system=TPP
PrimaryCareAdaptor -> TPP: Get Patient (IM1)
TPP --> PrimaryCareAdaptor: FHIR Patient
end
PrimaryCareAdaptor --> Application: FHIR Patient
else future (user = patient)
Application-> IPAAdaptor: Get Patient
IPAAdaptor-> EMIS: Get Patient (EMIS PFS)
EMIS --> IPAAdaptor: FHIR Patient
IPAAdaptor --> Application: FHIR Patient
end
Application -> User: Populate patient banner












@enduml
