@startuml


class "[[StructureDefinition-ServiceRequest-Referral.html ServiceRequest-Referral]]" as ServiceRequest <<aggregate root>> {
subject: must have NHS Number
code : Procedure code (UK SNOMED CT)
supportingInfo[referralForm] : RS-Referral-Request Form
supportingInfo[referralLetter] : Referral Letter
performer: Organisation(Identifier) or HealthcareService(Identifier)
}

class "[[Questionnaire-eRS-Referral-Request.html eRS-Referral-Request Form]]" as form <<entity>> {
}

class "[[Bundle-FHIRDocumentEOLCCarePlanBundle.html Referral Letter]]" as Composition <<entity>> {
}

class "Healthcare Service" as service

class Organization {
}

ServiceRequest "supportingInfo[referralForm]" --> form
ServiceRequest "supportingInfo[referralLetter]" --> Composition
ServiceRequest "performer" -u-> service
ServiceRequest "performer" -u-> Organization

@enduml
