
FSHOnly: false

  # ╭─────────────────────────Commonly Used ImplementationGuide Properties───────────────────────────╮
  # │  The properties below are used to create the ImplementationGuide resource. The most commonly   │
  # │  used properties are included. For a list of all supported properties and their functions,     │
  # │  see: https://fshschool.org/docs/sushi/configuration/.                                         │
  # ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: virtually.healthcare
canonical: https://fhir.virtually.healthcare
name: Virtually Healthcare Implementation Guide

title: Virtually Healthcare Implementation Guide

# description: Example Implementation Guide for getting started with SUSHI
status: draft
version: 0.0.1
fhirVersion: 4.0.1
copyrightYear: 2024+
releaseLabel: ci-build
license: Apache-2.0
jurisdiction: urn:iso:std:iso:3166#GB "United Kingdom of Great Britain and Northern Ireland"
publisher:
  name: Virtually Healthcare
  url: https://virtually.healthcare


# The dependencies property corresponds to IG.dependsOn. The key is the
# package id and the value is the version (or dev/current). For advanced
# use cases, the value can be an object with keys for id, uri, and version.
#
dependencies:
  fhir.r4.ukcore.stu2:
    version: 2.1.0
    uri: https://simplifier.net/guide/ukcoreversionhistory
  hl7.fhir.uv.sdc:
   version: 3.0.0
  hl7.fhir.extensions.r5:
    id: r5ext
    version: 4.0.1
    reason: |
      Makes available certain R5 elements for use as part of this R4 IG

parameters:  # see https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters
  path-resource:
    - input/resources
    - fsh-generated/resources
    - input/examples
  path-pages:
    - input/pagecontent
    - input/intro-notes
    - fsh-generated/includes
  show-inherited-invariants: 'false'
  usage-stats-opt-out: 'false'
  logging: progress
  shownav: 'true'
  active-tables: 'false'
  apply-contact: 'true'
  apply-jurisdiction: 'true'
  apply-publisher: 'true'
  apply-version: 'true'
  excludexml: 'false'
  excludejsn: 'false'
  excludettl: 'true'
  excludemap: 'true'
  excludeexample: 'false'
  generate:
    - xml
    - json

instanceOptions:
  setMetaProfile: never

menu:
  Home: index.html
  FHIR Assets: artifacts.html

resources:
  Patient/3:
    name: Patient-EMIS-IM1-Daniel-ODonnell
    description: EMIS IM1 Patient Daniel O'Donnell
    exampleBoolean: true
  Patient/1bec52a2-1bea-452f-a6ba-5eea5f97a24e:
    name: Patient-EMIS-PFS-Daniel-ODonnell
    description: EMIS PFS Patient Daniel O'Donnell
    exampleBoolean: true
  Patient/1107:
    name: Patient-TPP-IM1-Anthony-Avocet
    description: TPP IM1 Anthony  Avocet
    exampleBoolean: true
  Condition/3150:
    name: Condition-EMIS-IM1-Cardiovascular-event-risk
    description: Condition EMIS IM1 Cardiovascular event-risk
    exampleBoolean: true
  Condition/c60ea075-9992-4566-a314-b0fd27317310:
    name: Condition-EMIS-PFS-Cardiovascular-event-risk
    description: Condition EMIS PFS Cardiovascular event-risk
    exampleBoolean: true
  Observation/9e77f499-1081-4ec5-ad71-4eeb71bd25ba:
    name: Observation-EMIS-PFS-Weight
    description: Observation EMIS PFS Weight
    exampleBoolean: true
  Observation/3195:
    name: Observation-EMIS-IM1-Weight
    description: Observation EMIS IM1 Weight
    exampleBoolean: true
  Observation/3114:
    name: Observation-EMIS-IM1-Systolic-blood-pressure
    description: Observation EMIS IM1 Systolic blood pressure
    exampleBoolean: true
  Observation/3205:
    name: Observation-EMIS-IM1-Urine-protein-test-not-done
    description: Observation EMIS IM1 Urine protein test not done
    exampleBoolean: true
  Observation/4e197ae7-980e-4a76-979e-b94f952f1a65:
    name: Observation-EMIS-PFS-Urine-protein-test-not-done
    description: Observation EMIS PFS Urine protein test not done
    exampleBoolean: true
  Observation/367:
    name: Observation-EMIS-IM1-Plasma-glucose-level
    description: Observation EMIS IM1 Plasma glucose level
    exampleBoolean: true
  Observation/38431685-28e9-4cd0-854a-3ae0cb133264:
    name: Observation-EMIS-PFS-Plasma-glucose-level
    description: Observation EMIS PFS Plasma glucose level
    exampleBoolean: true
  DocumentReference/3214:
    name: DocumentReference-EMIS-IM1-Letter
    description: DocumentReference EMIS IM1 Weight
    exampleBoolean: true
  DocumentReference/ad1fcc5e-e9c6-491e-a12c-09085129c04c:
    name: DocumentReference-EMIS-PFS-Letter
    description: DocumentReference EMIS PFS Weight
    exampleBoolean: true
  Practitioner/4:
    name: Practitioner-EMIS-IM1-Pauline-Steele
    description: Practitioner EMIS IM1 Pauline Steele
    exampleBoolean: true
  MedicationRequest/4a71ace9-4d16-4dfb-8097-d7c78dc7ea7d:
    name: MedicationRequest-EMIS-PFS-Atorvastatin-10mg-tablets
    description: MedicationRequest EMIS PFS Atorvastatin 10mg tablets
    exampleBoolean: true
