
FSHOnly: false

  # ╭─────────────────────────Commonly Used ImplementationGuide Properties───────────────────────────╮
  # │  The properties below are used to create the ImplementationGuide resource. The most commonly   │
  # │  used properties are included. For a list of all supported properties and their functions,     │
  # │  see: https://fshschool.org/docs/sushi/configuration/.                                         │
  # ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: virtually.healthcare
canonical: https://fhir.virtually.healthcare
name: Virtually Healthcare Implementation Guide

title: Virtually Healthcare Implementation Guide

# description: Example Implementation Guide for getting started with SUSHI
status: draft
version: 0.0.1
fhirVersion: 4.0.1
copyrightYear: 2024+
releaseLabel: ci-build
license: Apache-2.0
jurisdiction: urn:iso:std:iso:3166#GB "United Kingdom of Great Britain and Northern Ireland"
publisher:
  name: Virtually Healthcare
  url: https://virtually.healthcare


# The dependencies property corresponds to IG.dependsOn. The key is the
# package id and the value is the version (or dev/current). For advanced
# use cases, the value can be an object with keys for id, uri, and version.
#
dependencies:
  fhir.r4.ukcore.stu2:
    version: 2.1.0
    uri: https://simplifier.net/guide/ukcoreversionhistory
  hl7.fhir.uv.sdc:
   version: 3.0.0
  hl7.fhir.extensions.r5:
    id: r5ext
    version: 4.0.1
    reason: |
      Makes available certain R5 elements for use as part of this R4 IG

parameters:  # see https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters
  path-resource:
    - input/resources
    - fsh-generated/resources
    - input/examples
  path-pages:
    - input/pagecontent
    - input/intro-notes
    - fsh-generated/includes
  show-inherited-invariants: 'false'
  usage-stats-opt-out: 'false'
  logging: progress
  shownav: 'true'
  active-tables: 'false'
  apply-contact: 'true'
  apply-jurisdiction: 'true'
  apply-publisher: 'true'
  apply-version: 'true'
  excludexml: 'false'
  excludejsn: 'false'
  excludettl: 'true'
  excludemap: 'true'
  excludeexample: 'false'
  generate:
    - xml
    - json

instanceOptions:
  setMetaProfile: never

menu:
  Home: index.html
  FHIR Assets: artifacts.html

resources:
  Patient/3:
    name: Patient-EMIS-IM1-3
    description: EMIS IM1 Patient 3
    exampleBoolean: true
  Patient/1bec52a2-1bea-452f-a6ba-5eea5f97a24e:
    name: Patient-EMIS-IM1-1bec52a2-1bea-452f-a6ba-5eea5f97a24e
    description: EMIS IM1 Patient 1bec52a2-1bea-452f-a6ba-5eea5f97a24e (EMIS IM1 Patient 3)
    exampleBoolean: true
