
FSHOnly: false

  # ╭─────────────────────────Commonly Used ImplementationGuide Properties───────────────────────────╮
  # │  The properties below are used to create the ImplementationGuide resource. The most commonly   │
  # │  used properties are included. For a list of all supported properties and their functions,     │
  # │  see: https://fshschool.org/docs/sushi/configuration/.                                         │
  # ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: virtually.healthcare
canonical: https://fhir.virtually.healthcare
name: Virtually Healthcare HL7 FHIR Implementation Guide

title: Virtually Healthcare HL7 FHIR R4 Implementation Guide

# description: Example Implementation Guide for getting started with SUSHI
status: draft
version: 0.1.0-current
fhirVersion: 4.0.1
copyrightYear: 2024+
releaseLabel: ci-build
license: Apache-2.0
jurisdiction: urn:iso:std:iso:3166#GB "United Kingdom of Great Britain and Northern Ireland"
publisher:
  name: Virtually Healthcare
  url: https://virtually.healthcare


# The dependencies property corresponds to IG.dependsOn. The key is the
# package id and the value is the version (or dev/current). For advanced
# use cases, the value can be an object with keys for id, uri, and version.
#
dependencies:
  fhir.r4.ukcore.stu3.currentbuild:
    version: 0.0.15-pre-release
    uri: https://simplifier.net/guide/ukcoreversionhistory
  hl7.fhir.uv.sdc:
   version: 3.0.0
  hl7.fhir.extensions.r5:
    id: r5ext
    version: 4.0.1
    reason: |
      Makes available certain R5 elements for use as part of this R4 IG

parameters:  # see https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters
  path-resource:
    - input/resources
    - fsh-generated/resources
    - input/examples
  path-pages:
    - input/pagecontent
    - input/intro-notes
    - fsh-generated/includes
  show-inherited-invariants: 'false'
  usage-stats-opt-out: 'false'
  logging: progress
  shownav: 'true'
  active-tables: 'false'
  apply-contact: 'true'
  apply-jurisdiction: 'true'
  apply-publisher: 'true'
  apply-version: 'true'
  excludexml: 'false'
  excludejsn: 'false'
  excludettl: 'true'
  excludemap: 'true'
  excludeexample: 'false'
  generate:
    - xml
    - json

instanceOptions:
  setMetaProfile: never

pages:
  index.md:
    title: Home
    generation: markdown
  clinical-data-repository.md:
    title: Clinical Data Repository
    generation: markdown
  Personal-Demographics-Service.md:
    title: Personal Demographics Service Facade (NHS England)
    generation: markdown
  Organisation-Data-Service.md:
    title: Organisation Data Service Facade (NHS England)
    generation: markdown
  e-Referral-Service.md:
    title: e-Referral Service Facade (NHS England)
    generation: markdown
  IM1-Transaction-EMIS.md:
    title: IM1 Transaction EMIS
    generation: markdown
  IM1-Patient-EMIS.md:
    title: IM1 Patient EMIS
    generation: markdown
  IM1-Transaction-TPP.md:
    title: IM1 Transaction TPP
    generation: markdown
  data-model.md:
    title: Data Model
    generation: markdown
  observation-definitions.md:
    title: Observation Panel
    generation: markdown




resources:
  Patient/3:
    name: Patient-EMIS-IM1-Daniel-ODonnell
    description: EMIS IM1 Patient Daniel O'Donnell
    exampleBoolean: true
  Patient/637:
    name: Patient-EMIS-IM1-William-Dyer
    description: EMIS IM1 Patient William Dyer
    exampleBoolean: true
  Patient/610:
    name: Patient-EMIS-IM1-Arthur-Thomas
    description: EMIS IM1 Patient Arthur Thomas
    exampleBoolean: true
  Patient/1bec52a2-1bea-452f-a6ba-5eea5f97a24e:
    name: Patient-EMIS-PFS-Daniel-ODonnell
    description: EMIS PFS Patient Daniel O'Donnell
    exampleBoolean: true
  Patient/1107:
    name: Patient-TPP-IM1-Anthony-Avocet
    description: TPP IM1 Anthony Avocet
    exampleBoolean: true
  Patient/500029:
    name: Patient-TPP-IM1-Anne-Smith
    description: TPP IM1 Anne Smith
    exampleBoolean: true
  Patient/9876543210:
    name: Patient NHSEngland - Matthew Sheppard (9876543210)
    description: Patient [NHS England PDS FHIR Api - OAS Specification](https://digital.nhs.uk/developer/api-catalogue/personal-demographics-service-fhir) Matthew Sheppard (9876543210)
    exampleBoolean: true
  Patient/9449304424:
    name: Patient NHSEngland - COMFORT26th Jones26th (9449304424)
    description: Patient [NHS England PDS FHIR Api - Int Environment](https://digital.nhs.uk/developer/api-catalogue/personal-demographics-service-fhir) COMFORT26th Jones26th (9449304424)
    exampleBoolean: true
  Patient/9449310424:
    name: Patient NHSEngland - pdsautomation automation edited (9449310424) Superseded
    description: Patient [NHS England PDS FHIR Api - Int Environment](https://digital.nhs.uk/developer/api-catalogue/personal-demographics-service-fhir) pdsautomation automation edited (9449310424) **Superseded** by 9449310416
    exampleBoolean: true
  Condition/3150:
    name: Condition-EMIS-IM1-Cardiovascular-event-risk
    description: Condition EMIS IM1 Cardiovascular event-risk
    exampleBoolean: true
  Condition/c60ea075-9992-4566-a314-b0fd27317310:
    name: Condition-EMIS-PFS-Cardiovascular-event-risk
    description: Condition EMIS PFS Cardiovascular event-risk
    exampleBoolean: true
  Condition/50002941:
    name: Condition-EMIS-IM1-Hypertension-monitoring
    description: Condition EMIS IM1 Hypertension monitoring
    exampleBoolean: true
  Observation/9e77f499-1081-4ec5-ad71-4eeb71bd25ba:
    name: Observation-EMIS-PFS-Weight
    description: Observation EMIS PFS Weight
    exampleBoolean: true
  Observation/3195:
    name: Observation-EMIS-IM1-Weight
    description: Observation EMIS IM1 Weight
    exampleBoolean: true
  Observation/3114:
    name: Observation-EMIS-IM1-Systolic-blood-pressure
    description: Observation EMIS IM1 Systolic blood pressure
    exampleBoolean: true
  Observation/cb41876b-ce8e-40c2-b6c1-1351d3e4e04a:
    name: Observation-EMIS-PFS-Systolic-blood-pressure
    description: Observation EMIS PFS Systolic blood pressure
    exampleBoolean: true
  Observation/3205:
    name: Observation-EMIS-IM1-Urine-protein-test-not-done
    description: Observation EMIS IM1 Urine protein test not done
    exampleBoolean: true
  Observation/4e197ae7-980e-4a76-979e-b94f952f1a65:
    name: Observation-EMIS-PFS-Urine-protein-test-not-done
    description: Observation EMIS PFS Urine protein test not done
    exampleBoolean: true
  Observation/367:
    name: Observation-EMIS-IM1-Plasma-glucose-level
    description: Observation EMIS IM1 Plasma glucose level
    exampleBoolean: true
  Observation/38431685-28e9-4cd0-854a-3ae0cb133264:
    name: Observation-EMIS-PFS-Plasma-glucose-level
    description: Observation EMIS PFS Plasma glucose level
    exampleBoolean: true
  DocumentReference/3214:
    name: DocumentReference-EMIS-IM1-Letter
    description: DocumentReference EMIS IM1 Letter encounter
    exampleBoolean: true
  DocumentReference/ad1fcc5e-e9c6-491e-a12c-09085129c04c:
    name: DocumentReference-EMIS-PFS-Letter
    description: DocumentReference EMIS PFS Letter encounter
    exampleBoolean: true
  Practitioner/4:
    name: Practitioner-EMIS-IM1-Pauline-Steele
    description: Practitioner EMIS IM1 Pauline Steele
    exampleBoolean: true
  Practitioner/achawla0309 :
    name: Practitioner-TPP-IM1-Amit-Chawla
    description: Practitioner TPP IM1 Amit Chawla
    exampleBoolean: true
  MedicationRequest/4a71ace9-4d16-4dfb-8097-d7c78dc7ea7d:
    name: MedicationRequest-EMIS-PFS-Atorvastatin-10mg-tablets
    description: MedicationRequest EMIS PFS Atorvastatin 10mg tablets
    exampleBoolean: true
  MedicationRequest/50002932:
    name: MedicationRequest-EMIS-IM1-Amoxicillin-125mg/5ml-oral-suspension-sugar-free
    description: MedicationRequest EMIS IM1 Amoxicillin 125mg/5ml oral suspension sugar free
    exampleBoolean: true
  Task/610595:
    name: Task-EMIS-IM1-Elderly-health-assessment
    description: Task-EMIS IM1 Elderly health assessment
    exampleBoolean: true
  Task/610596:
    name: Task-EMIS-IM1-Medication-review
    description: Task EMIS IM1 Medication review
    exampleBoolean: true
  Questionnaire/VitalSigns:
    name: Questionnaire-VitalSigns
    description: Questionnaire Vital Signs Definitions based on [NHS England Clinical Observations](https://simplifier.net/guide/ClinicalObservations/Home)
    exampleBoolean: false
  Questionnaire/ExerciseActivity:
    name: Questionnaire-ExerciseActivity
    description: Questionnaire Exercise Activity based on activity based measures from [HL7 Physical Activity Implementation Guide](https://build.fhir.org/ig/HL7/physical-activity/)
    exampleBoolean: false
  Questionnaire/DailyPhysicalActivity:
    name: Questionnaire-DailyPhysicalActivity
    description: Questionnaire Daily Physical Activity based on time based measures from [HL7 Physical Activity Implementation Guide](https://build.fhir.org/ig/HL7/physical-activity/)
    exampleBoolean: false
  Questionnaire/eRS-Referral-Request:
    name: Questionnaire-eRSReferralRequest
    description: Data capture definition for [A011 Create Referral (Deprecated)](https://developer.nhs.uk/apis/e-Referrals/explore_endpoint_a011.html)
    exampleBoolean: false
  Questionnaire/PDSPatientPreferences:
    name: Questionnaire-PDSPatientPreferences
    description: PDS Patient Preferences - refactor of none demographics extensions in PDS Patient API
    exampleBoolean: false
  Task/Task-EMIS-PFS-Prescription-Refill:
    name: Task-EMIS-PFS-Prescription-Refill
    description: Task EMIS PFS Prescription Refill
    exampleBoolean: true
  Immunization/610266:
    name: Immunization-EMIS-IM1-Pneumococcal-vaccination-declined
    description: Immunization EMIS IM1 Pneumococcal vaccination declined
    exampleBoolean: true
  Immunization/610281:
    name: Immunization-EMIS-IM1-Influenza vaccination
    description: Immunization EMIS IM1 Influenza vaccination
    exampleBoolean: true
  Organization/RR8:
    name: Organization NHS England - Leeds Teaching Trust (RR8)
    description: Organization [NHS England ODS FHIR Api](https://digital.nhs.uk/developer/api-catalogue/organisation-data-service-fhir) - Leeds Teaching Trust (RR8)
    exampleBoolean: true
  Organization/C81010:
    name: Organization NHS England - The Moir Medical Centre (C81010)
    description: Organization [NHS England ODS FHIR Api](https://digital.nhs.uk/developer/api-catalogue/organisation-data-service-fhir) - The Moir Medical Centre (C81010)
    exampleBoolean: true
  Composition/361:
    name: Composition EMIS IM1
    description: Composition EMIS IM1
    exampleBoolean: true
  Bundle/610161:
    name: FHIR Document EMIS IM1 Consultation Note
    description: FHIR Document EMIS IM1 Consultation Note
    exampleBoolean: true
  Bundle/361:
    name: FHIR Document EMIS IM1 Consultation Note 8 Nov 2024
    description: FHIR Document EMIS IM1 Consultation Note 8 Nov 2024
    exampleBoolean: true
#groups:
#  -ex-cdr:
#    name: "Clinical Data Repository Examples"
#    description: "Clinical Data Repository Examples"
#    resources:
#      Patient/073eef49-81ee-4c2e-893b-bc2e4efd2630
#      Organization/e2d3115b-402b-45a5-a01d-7acb64466ddc
#      - Observation/8f750590-30d6-425f-a8c4-f0a7c41e01d4
#      - Observation/71fae5af-0b9e-4b9e-b6af-3d1bb4e223a0
#      - Observation/cffe1a6e-8eda-4613-bf54-119b374bb5b9
#      - Observation/35eb7da3-9b85-46ce-bd29-75c2263b514a
#      - Observation/ad7c1832-f855-4ece-a4c7-c79b433a7890

menu:
  Home: index.html
  Adaptors:
    Clinical Data Repository:  clinical-data-repository.html
    Personal Demographics Service: Personal-Demographics-Service.html
    Organisation Data Service: Organisation-Data-Service.html
    e-Referral Service: e-Referral-Service.html
    IM1 Transaction - EMIS: IM1-Transaction-EMIS.html
    IM1 Patient - EMIS: IM1-Patient-EMIS.html
    IM1 Transaction - TPP: IM1-Transaction-TPP.html
  Domain Model:
    Data Model: data-model.html
    Observation Panel: observation-definitions.html
  FHIR Assets: artifacts.html
